# get all users
GET http://localhost:3003/api/blogs HTTP/1.1
###

#create new blog

POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Inl5ZCIsImlkIjoiNjM0YWM2NzU2OTg4NDIzYTU5MGE4ZTkyIiwiaWF0IjoxNjY1OTEwNDMzfQ.lsIoJsmhqdTEWP8Vej_Nwyv6oE2PJnWarIeCFxkMvM

{
    "title": "asdf",
    "author": "yysdfa",
    "url": "http://asavod.net/uj",
    "likes": 1
}
