
@hostname = localhost
@port = 3003
@host = {{hostname}}:{{port}}
@contentType = application/json

# get all users
GET http://{{host}}/api/users

###

# create new user

POST http://{{host}}/api/users
Content-Type: {{contentType}}

{
    "username":"Ruth Keller",
    "name":"Richard Gilbert",
    "password":"123456"
}
